// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHbPswVhhlSXMPhipFBQCEOTXFOvWaD0',
    appId: '1:715499978906:web:4e4a4a8c9861da8d6b9f23',
    messagingSenderId: '715499978906',
    projectId: 'my-phone-40ou',
    authDomain: 'my-phone-40ou.firebaseapp.com',
    storageBucket: 'my-phone-40ou.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyoYSq-J3P-d7SVAvDYkdNlcxj9FsUHdc',
    appId: '1:715499978906:android:6bb5357cb0529d716b9f23',
    messagingSenderId: '715499978906',
    projectId: 'my-phone-40ou',
    storageBucket: 'my-phone-40ou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMamopW35yhAMCiV1K3ck5ua9lbtPM9lY',
    appId: '1:715499978906:ios:4e75cf55eea7d7e46b9f23',
    messagingSenderId: '715499978906',
    projectId: 'my-phone-40ou',
    storageBucket: 'my-phone-40ou.appspot.com',
    iosClientId: '715499978906-9sp95i752jfmoc00gg0f6pkf4md4f2tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myphoneAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMamopW35yhAMCiV1K3ck5ua9lbtPM9lY',
    appId: '1:715499978906:ios:4e75cf55eea7d7e46b9f23',
    messagingSenderId: '715499978906',
    projectId: 'my-phone-40ou',
    storageBucket: 'my-phone-40ou.appspot.com',
    iosClientId: '715499978906-9sp95i752jfmoc00gg0f6pkf4md4f2tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myphoneAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxHbPswVhhlSXMPhipFBQCEOTXFOvWaD0',
    appId: '1:715499978906:web:3368f9926aefa1276b9f23',
    messagingSenderId: '715499978906',
    projectId: 'my-phone-40ou',
    authDomain: 'my-phone-40ou.firebaseapp.com',
    storageBucket: 'my-phone-40ou.appspot.com',
  );

}